### ISSUE TITLE
Docker Build Issues

### ISSUE THREAD

**Issue by md185331** [benweissmann/memongo#10]
When building docker I am getting an error when executing the tests. The package pulls down the mongo binary and stores it in a local folder in the project but when running the tests I get this folderName/mongo.tgz/mongod: no such file or directory. 

// Code that sets up the memongo server. The dir is a folder in the project its self. This code is ran for each test as in each test is independent and calls the memongo.startWithOptions(...).  Without docker all tests run and pass no errors ad the memongo package works fine. When building the docker image it fails.	
mongoServer, err := memongo.StartWithOptions(&memongo.Options{
		CachePath:    dir,
		MongoVersion: "4.0.5",
	})

**Comment by benweissmann** [comment]
When opening an issue like this, it's best to include a [minimal reproduction](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) to make it straightforward to understand the bug. I can't tell very much from the small snippet you've included. I'd suggest reading through the [Configuration section of the README](https://github.com/benweissmann/memongo#configuration) and try some of those options, like manually specifying the URL of the MongoDB binary.

In general, I'm not able to test memongo in every possible environment (although I do have Vagrant set up to test it in [a lot of environments](https://github.com/benweissmann/memongo/tree/master/vagrant)), and don't have the bandwidth to support additional environment. But I'm happy to review a pull request that adds support for additional environments!
